# Generated by Django 5.0 on 2024-04-19 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_reply', '0002_alter_offer_price'),
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='query',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='query.query'),
        ),
    ]
