# Generated by Django 5.0 on 2024-01-08 16:27

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(3)])),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('authors', models.ManyToManyField(related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
