# Generated by Django 5.0 on 2024-04-21 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_article_edited_on_alter_article_published_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='authors',
            new_name='user',
        ),
    ]
