# Generated by Django 5.0 on 2024-01-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuserprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuserprofile',
            name='company_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
