# Generated by Django 5.0 on 2024-01-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appuserprofile_company_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='company_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
