# Generated by Django 5.0 on 2024-01-08 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_appuserprofile_company_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(50)]),
        ),
    ]
