# Generated by Django 5.0 on 2024-01-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_appuserprofile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuserprofile',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
