# Generated by Django 5.0 on 2024-04-16 08:20

import django.core.validators
import validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='projects/', validators=[validators.MaxImageSizeValidator(5.0)])),
                ('description', models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(10)])),
                ('location', models.CharField(max_length=30)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('date_of_publication', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
