# Generated by Django 5.0 on 2024-04-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_of_publication',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
